### ISSUE TITLE
Seperating tests

### ISSUE THREAD

**Issue by william-man** [fac30/discord-ai-bot--kieran-ollie#32]
Currently your test file contains tests that may or may not be relevant to each other and adding more tests into the same file will likely make it very difficult to find which test is failing. Strongly recommend creating a folder and specific files for each test to make your life easier.

(similar issue with the index file)

**Comment by zz-hh-aa** [comment]
`test` folder with eg `openai` or `discord` tests, all ending in `.test.js`
